apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-cephfs-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-cephfs
---
apiVersion: v1
kind: Pod
metadata:
  name: csi-cephfs-test-pod
spec:
  containers:
    - name: busybox
      image: busybox
      args:
      - sh
      - -c 
      - "sleep 3600"
      volumeMounts:
        - name: mypvc
          mountPath: /mnt/pvc
  volumes:
    - name: mypvc
      persistentVolumeClaim:
        claimName: csi-cephfs-pvc
        readOnly: false